Repository dwyl/cid, pull requests merged in 2019-01, with the labels that each got.

#12 adds section about youtube to readme #9
  README.md
Labels: awaiting-review

#16 Add detail
  README.md
  lib/cid.ex
  mix.exs
  mix.lock
Labels: awaiting-review, enhancement

#20 Faqs
  README.md
  real_world_examples.md
Labels: awaiting-review

#21 Create cid
  .travis.yml
  README.md
  lib/cid.ex
  mix.exs
  mix.lock
  test/cid_test.exs
Labels: in-review

#25 adds codecov and travis build badges
  .travis.yml
  README.md
  coveralls.json
  mix.exs
Labels: awaiting-review

#29 Codecov badge
  README.md
  mix.exs
Labels: awaiting-review

#30 Use b58 dependency
  lib/cid.ex
  mix.exs
  mix.lock
Labels: awaiting-review

#32 First release
  README.md
  mix.exs
  mix.lock
Labels: awaiting-review

#33 change the package name #31
  README.md
  mix.exs
  test/cid_test.exs
Labels: awaiting-review
